# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c9aea26572af130c7f0890e709a2526b1080ca4013e68ca4ec4678e8d206f5c87963d8172f7566f41bf5517f9b2a7e8a4dfb113ec776f04fce23fbfc304bdd

test:
  secret_key_base: c383880425bcf72d908bfe757f22a4b5f4d75b7d5e44788621cf0309a9db83d92e494937f59b964f16e0a6399437e31e1453f815edbb6734ec8ddad3895bd425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
